### ISSUE TITLE
Gawin nyo na yung sa User Dashboard.

### ISSUE THREAD

**Issue by RonJeffrey** [RonJeffrey/itelec2#3]
Gawin nyo na yung sa User Dashboard. ichecheck ko sila isa isa then try kong pag samasamahin mga Idea nyo. Thank you!

**Comment by kenchaoma55** [comment]
yung tipong na ka code naba ang gagawin or concept design?

**Comment by RonJeffrey** [comment]
kahit design lang sya aq na bala nun
